### ISSUE TITLE
pressing down arrow should zoom out

### ISSUE THREAD

**Issue by JamesDarby345** [MosheLevy20/VolumeAnnotate#5]
Switching the Radio Buttons or Normal Button Groups is taking priority over the zoom in and out when using the arrow keys, once at the end of the group the zoom in and out work again.

Example: If you have the Pan radio selected and focussed, pressing down arrow cycles through the options before zooming out.
![image](https://user-images.githubusercontent.com/49734270/234284605-80b660e3-ebef-4710-b5be-b7eb67db8c98.png)
![image](https://user-images.githubusercontent.com/49734270/234284448-8428ceb0-8b7c-4872-9e30-c6b9b2e917dd.png)

**Comment by JamesDarby345** [comment]
Vice versa for the up arrow, also an issue if you press any of the other grouped buttons

**Comment by MosheLevy20** [comment]
Couldn't reproduce this issue. I'm on Mac

**Comment by JamesDarby345** [comment]
Interesting, I'm on Windows so maybe the UI behaves a bit differently. This is more a quality of life bug.
